export type FieldNote = {
  slug: string;
  number: string;
  date: string;
  title: string;
  summary: string;
  source?: string;
  image?: { src: string; alt: string; width: number; height: number };
  references?: { label: string; url: string }[];
  body: string[];
  closing?: string;
};

export const FIELD_NOTES: FieldNote[] = [
  {
    slug: 'before-i-trust-a-backtest-i-check-the-data',
    number: 'NOTE 013',
    date: '2026-09-17',
    title: 'Before I Trust a Backtest, I Check the Data',
    summary:
      'Building a small options-data check in Green Machine taught me to ask what a result can actually support before asking how much it could make.',
    source: 'Green Machine / Research Memo 006',
    references: [
      {
        label: 'Reproduced synthetic fixture results and methodology — September 17, 2026 (JSON)',
        url: '/research/options-data-quality-2026-09-17.json',
      },
    ],
    body: [
      'I trade options, and I build software. Those two parts of my work meet in a question I keep coming back to: what would make me trust this result?',
      'A backtest can produce a smooth curve and precise statistics. Before I take those numbers seriously, I need to know what went into them. Which quotes were available? Which observations are missing? What price does the simulation assume I could have traded?',
      'In Green Machine, my research software, I built a small check for options and intraday datasets. I called it the options honesty study. Its job is to flag basic problems before I move on to testing a trading idea.',
      'The first version checks whether required columns exist, whether there is enough date and row coverage under the configured thresholds, and how much of the required numerical feature data is missing. It also flags negative bids, nonpositive asks, crossed quotes where the ask is below the bid, and a high proportion of wide spreads.',
      'The spread matters because a quoted midpoint is not a guaranteed execution price. Consider a hypothetical option with a $1.00 bid and a $1.20 ask. Its midpoint is $1.10. A simulation that assumes I can buy and sell at that midpoint needs evidence for that assumption. The quote alone does not provide it.',
      'For this prototype, I defined a wide spread as more than 20% of the midpoint. If more than 15% of observations exceed that threshold, the check issues a warning. These are configurable research choices. They are not universal standards or proof that the remaining quotes are tradable.',
      'The output has three states. FAIL identifies a blocking issue under these checks. WARN allows exploratory diagnostics while calling attention to execution assumptions. PASS means only that the dataset cleared this particular screen and can move to a controlled study. It says nothing about profitability.',
      'I tested the implementation with deliberately constructed examples. A 25-date fixture with complete fields and narrow spreads passed. A version with wide spreads in every fifth quote produced a warning. A three-date fixture failed the minimum-history check. Separate tests checked missing columns, crossed quotes, and missing numerical features. All six existing tests passed when rerun for this article.',
      'These are synthetic fixtures. They demonstrate that the tested branches behave as expected. They do not validate a historical options feed, establish realistic fills, or show a trading edge. The dates are generated using weekdays rather than a full exchange calendar.',
      'Reading the implementation also makes its limits concrete. It counts distinct dates across the two input tables; it does not prove that their observations match at the same times. A row count does not establish complete strike or expiration coverage. An average missing-value rate can hide a concentrated gap in one feature. Those distinctions matter before calling a dataset ready.',
      'There is more work to do: explicit timestamp and underlying alignment, exchange-session handling, duplicate and missing-quote checks, quote-age validation, and realistic execution-cost assumptions. This version also does not verify Greeks or whether every input was actually available at the moment a simulated decision would have been made.',
      'The next experiment is to bring a real historical dataset through those checks and inspect the rejected records. After that, I can test whether a defined setup separates future outcomes, using evaluation periods that were not used to choose the rule. Performance claims come later.',
      'This is the kind of work I want XIV to document: the question, the implementation, the result, and the remaining uncertainty. Sometimes the useful result is discovering that I cannot answer the trading question yet.',
      'Neither bull nor bear. I follow the evidence and manage the risk. That starts with checking the evidence itself.',
    ],
  },
  {
    slug: 'are-tech-companies-the-new-banks',
    number: 'NOTE 012',
    date: '2026-09-11',
    title: 'The AI Boom Is Tying Balance Sheets Together',
    summary:
      'Watching The Big Short led me to examine the financial ties behind the AI boom, how losses could spread, and what the government might choose to save.',
    image: {
      src: '/images/ai-blog/are-tech-companies-the-new-banks-no-portrait.png',
      alt: 'Marcelo Zapata’s bright editorial card comparing the 2008 bank collapse with the 2026 AI boom. A sunlit bank building connects to silver server racks under the question: Are tech companies the new banks? His name and a red-and-black XIV dragon appear above.',
      width: 1122,
      height: 1402,
    },
    references: [
      {
        label: 'Federal Reserve: interconnectedness and the financial crisis',
        url: 'https://www.federalreserve.gov/newsevents/speech/yellen20130104a.htm',
      },
      {
        label: 'U.S. Treasury: TARP and the response to the 2008 financial crisis',
        url: 'https://home.treasury.gov/data/troubled-assets-relief-program/about-tarp',
      },
      {
        label: 'CoreWeave filing: Nvidia as supplier, shareholder and capacity buyer',
        url: 'https://www.sec.gov/Archives/edgar/data/1769628/000176962825000047/crwv-20250909.htm',
      },
      {
        label: 'CoreWeave filing: Nvidia’s $2 billion investment',
        url: 'https://www.sec.gov/Archives/edgar/data/1769628/000176962826000044/crwv-20260123.htm',
      },
      {
        label: 'CoreWeave: $2.6 billion debt facility supporting its OpenAI agreement',
        url: 'https://investors.coreweave.com/news/news-details/2025/CoreWeave-Closes-2-6-Billion-Secured-Debt-Financing-Facility-Strengthening-Market-Position-as-AI-Cloud-Leader/default.aspx',
      },
      {
        label: 'NGA: AI for intelligence, surveillance and reconnaissance',
        url: 'https://www.nga.mil/news/NGA_announces_%24708M_data_labeling_RFP.html',
      },
      {
        label: 'NGA congressional testimony: AI and military targeting',
        url: 'https://www.nga.mil/news/Testimony_of_VADM_Frank_D_Whitworth_before_the_Hou.html',
      },
    ],
    body: [
      '2008 on the screen. 2026 on my mind.',
      'I watched The Big Short and saw dominoes.',
      'The banks were separate companies. Their risks were connected. Borrowing, guarantees and exposure to the same assets helped losses travel from one balance sheet to another.',
      'I see a similar pattern forming in parts of the AI buildout.',
      'Nvidia sells chips to CoreWeave. Nvidia owns shares in CoreWeave. Nvidia has agreed to buy unused CoreWeave computing capacity, subject to the contract’s conditions. In January, Nvidia put in another $2 billion.',
      'CoreWeave, in turn, secured a $2.6 billion debt facility to build infrastructure under its OpenAI agreement.',
      'Nvidia is a supplier, investor and capacity buyer. Outside lenders finance CoreWeave’s buildout. Different roles, connected bets.',
      'Now run the scenario forward. A major customer misses a payment. Its cloud provider loses expected revenue but still owes its lenders. Equipment orders slow. The pressure reaches suppliers.',
      'Several businesses can become dependent on the same demand arriving on schedule.',
      'The technology can work and the financing can still break. I want to understand both.',
      'Here is where I part ways with treating this as a repeat of 2008. These companies carry different debt loads, different cash reserves and different margins for error. A financial connection is a reason to examine the risk. It is not proof that everyone falls together.',
      'Government intervention belongs in the comparison, too. In 2008, Washington stepped in to stabilize the financial system.',
      'AI already supports military surveillance, intelligence analysis, and targeting. Its value to Washington goes well beyond what customers will pay for a subscription.',
      'My read: if that capability were threatened, the government would step in. A bailout is one form that could take. That is my judgment, not a promised rescue, and I would not build a position on the assumption.',
      'Protecting the infrastructure does not require protecting every company. Individual firms could fail while their data centers and other assets pass to new owners.',
      'The technology can survive. Investors can still lose.',
    ],
  },
  {
    slug: 'all-in-every-time',
    number: 'NOTE 011',
    date: '2026-09-05',
    title: 'All In, Every Time',
    summary:
      'Caring about the work, learning from feedback, and changing the approach when it helps.',
    body: [
      'I care deeply about what I build.',
      'I am learning that giving a project my best also means pacing the work, listening to feedback, and recognizing when an approach needs to change.',
      'This week, my visualization projects were in a rut. Repeating the same approach was not getting me closer to the result I wanted.',
      'Trying a different AI tool helped me make progress. It also reminded me that perseverance works better when I stay open to another method.',
      'Before I commit more time, I want to understand the cost, what progress would look like, and when I should ask for help or reconsider the plan.',
      'AI helps me explore quickly. I still need to review the result and stand behind what carries my name.',
      'All in, every time: care about the work, stay open to feedback, and keep learning.',
    ],
  },
  {
    slug: 'the-chat-box-is-only-the-top-floor',
    number: 'NOTE 010',
    date: '2026-09-04',
    title: 'The Chat Box Is Only the Top Floor',
    summary:
      'Your chatbot has a supply chain. A solarpunk look at the models, chips, factories, data centers, resources, and partnerships behind the chat box.',
    source: 'OpenAI partnership announcements: AMD, Oracle, and Amazon.',
    image: {
      src: '/images/ai-blog/the-chat-box-is-only-the-top-floor-solarpunk.png',
      alt: 'Solarpunk tower illustrating seven layers of the AI supply chain: products, developers, models and agents, chip design, chip manufacturing, data centers and cloud, and physical resources.',
      width: 1024,
      height: 1536,
    },
    references: [
      {
        label: 'OpenAI and AMD partnership',
        url: 'https://openai.com/index/openai-amd-strategic-partnership/',
      },
      {
        label: 'OpenAI and Oracle: Stargate infrastructure',
        url: 'https://openai.com/index/stargate-advances-with-partnership-with-oracle/',
      },
      {
        label: 'OpenAI and Amazon partnership',
        url: 'https://openai.com/index/amazon-partnership/',
      },
    ],
    body: [
      'AI Friday. Setting foundations.',
      'The chat box is only the top floor.',
      'You open ChatGPT, Claude, Gemini, or DeepSeek. You type a prompt. An answer appears.',
      'But underneath that interaction is a supply chain.',
      'Companies building models.',
      'Software connecting those models to tools.',
      'Chips running the computation.',
      'Factories manufacturing those chips.',
      'Data centers housing them.',
      'Electricity and cooling keeping everything running.',
      'NVIDIA and AMD design many of the chips used for AI. TSMC manufactures many of those designs. Cloud providers make computing capacity available to the companies building the products we use.',
      'And these relationships go beyond buying and selling hardware.',
      'OpenAI’s partnerships with AMD, Oracle, and Amazon connect the software to chip deployments, data center construction, and cloud infrastructure.',
      'So when I hear “AI company,” I’m learning to look beyond the app.',
      'Who supplies the chips?',
      'Where does the computing happen?',
      'What powers it?',
      'Who finances the infrastructure?',
      'As I build with AI, those questions matter alongside what a model can do. They help explain what it costs, how reliably it runs, and who can access it.',
      'The tower in this image is a simplified map. Some companies operate on several floors.',
      'I gave it a solarpunk setting because I like imagining a future where technology and the living world fit together. Building that future means understanding the physical resources behind the interface.',
      'The cloud lives somewhere.',
      'And the companies supplying the lower floors help shape what gets built upstairs.',
      'Day 4 of documenting what I learn building with AI.',
      'Farewell until tomorrow.',
    ],
  },
  {
    slug: 'ai-is-an-addictive-product-on-a-subscription',
    number: 'NOTE 009',
    date: '2026-09-03',
    title: 'Building AI Workflows That Can Adapt',
    summary:
      'What I am learning about usage limits, portability, and keeping AI-assisted work reviewable.',
    body: [
      'AI has become part of how I build. That makes reliability, cost, and portability practical engineering questions.',
      'In my own projects, I want to know what happens when a model is unavailable, a subscription changes, or a task uses more tokens than expected.',
      'A useful workflow needs more than a good prompt. It needs clear inputs, acceptance criteria, saved progress, and a way to review the result.',
      'I use a written project brief to describe what the system should become, what boundaries matter, and what done means. Keeping that context alongside the code helps me resume work across tools.',
      'Portability takes work. Models differ, integrations differ, and switching tools still requires validation. A shared brief helps preserve intent; it does not guarantee identical results.',
      'My next step is to make costs and failure modes easier to inspect: bounded tasks, recorded changes, and checks before accepting output.',
      'I want AI to help me move faster while keeping the work understandable to me and to anyone who may maintain it later.',
    ],
    closing: 'KEEP THE CONTEXT. CHECK THE RESULT.',
  },
  {
    slug: 'i-had-a-dream',
    number: 'NOTE 008',
    date: '2026-09-02',
    title: 'I Had a Dream',
    summary:
      'A calm experiment in letting AI agents carry repeatable execution while a human holds the vision, judgment, and life around the work.',
    body: [
      'Last night I slept. My code did not.',
      'Day 2 is not really about "AI agents worked while I slept."',
      'That is just the headline.',
      'The deeper shift is that AI changes where the human belongs in the work.',
      'The human job is not to grind beside the machine forever. It is to hold the dream clearly enough that the system can build toward it.',
      'Most people already have the hard part in their head: how they make decisions, what they care about, what good work looks like, what should never happen, what information matters before taking action, how they review mistakes, and how they know something is done.',
      'But it is scattered across memory, chats, documents, folders, and habits.',
      'The technical idea is simple.',
      'The dream file is the source of truth for the end state. It is not just a prompt. It is the project\'s operating contract. It tells the agents what the system is supposed to become, what matters, what boundaries cannot be crossed, and what "done" should feel like.',
      'Each agent loop follows the same rhythm: read the dream file, check the current repository, choose one bounded task, write the code, run the tests, review the changes, leave a receipt, and stop, continue, or report a blocker.',
      'None of them has asked for a raise. Yet.',
      'The repository tells me what exists.',
      'The dream file tells me what should exist.',
      'The receipts tell me what changed.',
      'That separation lets different tools work toward the same target without me carrying the entire project between chats all day.',
      'It is not magic. It makes mistakes. I check in every couple of hours, catch problems, redirect, and go back to my life.',
      'So I can make music, go swimming, walk Rosco, cut potatoes, and come back to judge the work.',
      'Rosco does not care about software. Rosco is correct.',
      'The agents can handle the repeatable loops. They cannot decide what is meaningful.',
      'They do not know why the walk matters. They do not know why the music has to feel like getting back into my body. They do not know why the world should feel alive when someone enters it, or why I want to stand in a quiet kitchen cutting vegetables with no rush before the market opens.',
      'That part is still mine.',
      'My job is the vision and the verdict. AI gets the work between those decisions.',
      'Day 2 of documenting what I learn building with AI. Tomorrow: the smallest version of this, built in public, step by step.',
      'What is the part of your work only you can do?',
      'Posting this now. There are potatoes to cut and an Alexander the Great documentary to watch. He also delegated.',
    ],
    closing: 'MY JOB IS THE VISION. AI GETS THE WORK BETWEEN DECISIONS.',
  },
  {
    slug: 'the-job-was-not-the-dream',
    number: 'NOTE 007',
    date: '2026-09-01',
    title: 'Building a Career and a Life',
    summary:
      'A reflection on meaningful work, continuous learning, and keeping room for life beyond a title.',
    body: [
      'I used to imagine that the right title would tell me I had made it.',
      'I still value meaningful work, stability, and the chance to learn alongside other people. I also want to keep growing beyond any one role.',
      'My experience in enterprise software gave me a foundation in integrations, quality, and the responsibility that comes with systems people depend on.',
      'I am carrying that experience into the next chapter: building projects, documenting what I learn, and looking for a team where I can contribute and continue developing.',
      'A career is part of a life. Music, learning, and time with the people I care about matter to me too.',
      'Independent projects give me another place to practice. I can choose a problem, build something small, test it, and share what worked and what still needs attention.',
      'AI can support that process, but the responsibility to learn, collaborate, and check the work remains mine.',
      'I want a career built on useful contributions, curiosity, and relationships with people who care about doing good work.',
    ],
    closing: 'KEEP LEARNING. KEEP BUILDING.',
  },
  {
    slug: 'my-big-bet',
    number: 'NOTE 006',
    date: '2026-08-30',
    title: 'My Big Bet',
    summary: 'Making AI useful through clear workflows, shared learning, and measurable results.',
    body: [
      'My bet is on helping people connect AI tools to real work.',
      'My background in enterprise software and quality assurance shapes how I approach that problem. A tool becomes useful when people understand where it fits, how to check its output, and who owns the result.',
      'I want to build workflows that a team can understand and maintain together. That means documenting useful patterns, sharing examples, and making room for questions.',
      'Training matters as much as access. People bring different experience to the same tool, and practical examples can help them find a starting point.',
      'I have also built an AI-assisted system for a local Miami business. That work reinforced the importance of understanding the daily operation before choosing an automation.',
      'When I describe impact, I want the evidence to be clear: the baseline, the measurement period, the outcome, and any extra work the system creates. Generating more output is not enough.',
      'The process I want to follow is simple: choose a real problem, build a small version, review it with the people using it, and measure whether it helps.',
      'I am interested in software engineering and QA roles where I can contribute that approach, learn from a team, and build reliable systems.',
      'The goal is useful software that gives people more room to do the work they care about.',
    ],
    closing: 'MAKE THE WORK USEFUL. MAKE THE LEARNING SHARED.',
  },
  {
    slug: 'fourteen',
    number: 'NOTE 005',
    date: '2026-08-27',
    title: 'Designing AI Workflows Around People',
    summary:
      'Exploring how automation can improve handoffs while preserving human judgment and accountability.',
    body: [
      'I am interested in how AI can reduce the effort of moving work between people.',
      'A handoff can involve gathering context, summarizing a request, checking a record, or routing a question. Those are useful places to explore automation.',
      'That does not tell me how many people a company needs. Staffing depends on demand, service quality, exceptions, domain expertise, and responsibilities that a workflow diagram can miss.',
      'For a small experiment, I would choose one repeatable queue and document how it works today. Then I would test whether an AI-assisted step improves turnaround without increasing errors or review work.',
      'People using the workflow should help design it. They know where the exceptions live and what information is easy to overlook.',
      'Before expanding the experiment, I would want clear ownership, escalation paths, access controls, and a way to recover when automation fails.',
      'The measures should include quality and the experience of the people doing the work, alongside time and cost.',
      'I do not have evidence for a specific headcount reduction. My question is narrower: can a well-tested workflow remove a frustrating handoff and let people spend more time on work that needs their judgment?',
      'That is an engineering problem worth exploring with the team, one bounded experiment at a time.',
    ],
    closing: 'IMPROVE THE HANDOFF. KEEP THE ACCOUNTABILITY.',
  },
  {
    slug: 'coding-beats',
    number: 'NOTE 004',
    date: '2026-08-24',
    title: 'Coding Beats',
    summary: 'A public study of rhythm written as code: patterns, motion, and measured sound.',
    source: 'MaloSound',
    body: [
      'I want to study beats that are written as code.',
      'Tools like Strudel make rhythm visible. A beat is not only an audio file. It is tempo, samples, rests, repetition, probability, filters, space, and timing written into a system.',
      'That matters because coded music can be inspected. Change one line and the beat changes. Save the pattern and the idea becomes repeatable. Compare two versions and you can hear what moved.',
      'That is the research question: what happens when a beat is treated like software and sound at the same time?',
      'The study is simple. Build small coded sketches. Document the pattern. Listen to the result. Measure the audio. Map the signal to movement or visuals.',
      'It is also a memory system. I can come back later and see the beat as code: the tempo, the rests, the drum choices, the filter shape, the space, and the pulse.',
      'Someone else can open the same sketch in Strudel, press play, and change it. That is different from posting an audio clip.',
      'The beat is not only something to hear. It is something to inspect.',
      'This is not a claim that AI understands music. It is a public study of how coded rhythm becomes measurable sound and movement.',
      'MaloSound is the public music lane for XIV. This note is the coded rhythm lane.',
      'The first sketch is a slow coded beat in Strudel: readable, playable, and changeable.',
    ],
    closing: 'The beat is not only something to hear. It is something to inspect.',
  },
  {
    slug: 'you-are-not-a-runner',
    number: 'NOTE 003',
    date: '2026-08-16',
    title: 'You Are Not a Runner',
    summary:
      'A note on the sentences that stop us learning something, and why experience outside our heads can change them.',
    source:
      'Jacques Hadamard, An Essay on the Psychology of Invention in the Mathematical Field, 1945.',
    body: [
      'A language model is made of language. That is not an insult. It is the whole description.',
      'It read what we wrote down. It predicts what comes next.',
      'It is very good at that. Most thinking is already written down somewhere.',
      'It has read more than I ever will. It answers in seconds what would take me a week.',
      'I use it every day and I am not being modest about that.',
      'There is nothing under the words. Ask it what it is and you get more words.',
      'For a model the words are not a container. They are the whole thing.',
      'We talk about ourselves the same way.',
      'At the halfway point of the Miami Marathon the course splits.',
      'Left is a finish line and a medal. Right is thirteen more miles.',
      'My legs had stopped working. Another thirteen felt impossible. What have I gotten myself into.',
      'Stop. You cannot do this. You are not a runner.',
      'The first two were about the race.',
      'The third one was about me.',
      'That sentence had been in my head for years. I never once checked it.',
      'You cannot argue with that one. The thing you argue with is the thing that wrote it.',
      'Einstein was asked how he actually thought.',
      'He said words had nothing to do with it. He worked in images. The words had to be found afterwards, laboriously.',
      'Afterwards.',
      'The words came last. They were never the thing.',
      'I went right.',
      'Thirteen more miles with the sentence still going.',
      'It never stopped. It stopped being true.',
      'Nothing in my head did that. Something outside it did.',
      'Months later I sat down to learn this technology from nothing.',
      'Hours at a desk. No crowd, no mile markers, nobody watching if I stopped.',
      'The same sentence showed up. This time I knew what it was.',
      'A model cannot be contradicted from outside its text. You can. You are not only text.',
      'Some days the sentence still wins. But one that has been proven wrong once never sounds the same.',
    ],
    closing: 'WORDS ARE CONTAINERS FOR COMMUNICATION. NOT IDENTITY.',
  },
  {
    slug: 'the-trap-of-time',
    number: 'NOTE 002',
    date: '2026-08-13',
    title: 'The Trap of Time',
    summary:
      'A useful label can become a room you stop trying to leave. A note on time, identity, and using AI to test your limits.',
    source: 'Up, dir. Pete Docter, Pixar, 2009.',
    body: [
      'Time is dangerous when you spend too much of it inside the same story.',
      'At first, a label is useful.',
      'Manager. Analyst. Marketer. Operator. Non-technical. Creative. Business person.',
      'It helps people understand what you do.',
      'But stay inside that label long enough, and it starts to feel like who you are.',
      'That is the trap of time.',
      'You do something for years or decades. You build a life around it. People recognize you for it. You get rewarded for staying consistent. Then one day, the world changes, and the label that once gave you structure starts keeping you in place.',
      'Someone who studied marketing can learn to work with campaign data. Someone from finance can build a small automation. Someone from design can prototype a workflow. The degree remains useful. It becomes context.',
      'That is what I think about with Carl in UP.',
      'He was not just an old man sitting in a house. He was someone frozen in time.',
      'The house was memory. The routine was safety. The dream was still there, but buried under years of grief, repetition, and identity.',
      'Then a push came.',
      'Not a full plan. Not a perfect roadmap. Not permission.',
      'A push.',
      'That is what AI can be for people right now.',
      'A push out of the version of yourself you accepted too early.',
      'Not because AI makes you someone else. Not because it removes the work. But because it lets you question the walls around your current identity.',
      'I am not technical. I am not good with data. I cannot build. That is not my role. It is too late to learn.',
      'How many of those are facts, and how many are just old sentences with time wrapped around them?',
      'The danger is not being bad at something. The danger is letting time convince you that you cannot become anything else.',
      'AI is shrinking the distance between curiosity and execution. You can ask. You can test. You can build. You can learn in private. You can step into rooms that used to feel locked.',
      'But only if you move.',
      'Because the trap is comfortable.',
      'It looks like stability. It sounds like experience. It feels like being realistic.',
      'But sometimes being realistic is just fear with a better outfit.',
      'Do not get caught sleeping inside a label.',
      'The tools are already here.',
      'Sometimes all you need is a push.',
    ],
    closing: 'The only way is UP.',
  },
  {
    slug: 'the-only-thing-paying-attention',
    number: 'NOTE 001',
    date: '2026-08-12',
    title: 'The Only Thing Paying Attention',
    summary:
      'The Axiom passengers were not lazy. They stopped looking up. A note on comfort, agency, and curiosity as an exit.',
    source: 'WALL-E, dir. Andrew Stanton, Pixar, 2008.',
    body: [
      'Everyone posts the Axiom frame to say people got lazy. That is not what the movie is about.',
      'The passengers were fine. Each had a screen a few inches from their face and a pool on board they never knew existed. Nothing was taken from them. They stopped looking up.',
      'Three people I know have three unrelated relationships to the same tool. At work I am more or less required to use it. My sister uses it as a therapist. The woman who rang me up at a sporting goods store last weekend may never have opened it once. Most arguments about whether AI matters are arguments between people whose days look nothing alike.',
      'Which suggests the tool has no fixed depth. It returns something shaped like whatever you walked up to it with - the question you already had, the problem you were already sitting on. The ceiling is set outside the model.',
      "So the failure mode isn't capability. It's comfort.",
      'Nobody takes your agency. You trade it, and the trade is good every single time. The draft comes back fine. The option is already selected. The sentence is already formed. No single exchange is a loss, which is exactly why the total is hard to see. Nothing that felt bad could spread this fast.',
      'WALL-E gave humanity seven hundred years to arrive at that ship.',
      "The captain breaks out of it, and how he does it is the part worth keeping. Nobody warns him. Nobody presents evidence. He gets curious about a plant, and about a word he doesn't know, and the whole system loses him in an afternoon. Curiosity is the only exit the film offers - and it isn't offered as a discipline. It's offered as an accident a person allowed.",
      'SO INSTEAD OF ASKING WHETHER AI IS A BIG DEAL:',
      'If this is a tool - how are we using it?',
      'Are we using it to explore our curiosity, or is it exploring us?',
    ],
    closing: 'Are we using it to explore our curiosity, or is it exploring us?',
  },
];

export function getFieldNote(slug: string) {
  return FIELD_NOTES.find((note) => note.slug === slug);
}
