export type FieldNote = {
  slug: string;
  number: string;
  date: string;
  title: string;
  summary: string;
  source?: string;
  body: string[];
  closing?: string;
};

export const FIELD_NOTES: FieldNote[] = [
  {
    slug: 'fourteen',
    number: 'NOTE 005',
    date: '2026-08-27',
    title: 'Fourteen',
    summary:
      'Nobody hired a thousand people because the work needed a thousand people. Headcount was a measurement of friction. That is the thing collapsing.',
    body: [
      'The layoff argument is about tasks. Which tasks a model can do. That is the wrong unit.',
      'The unit is the company.',
      'Nobody ever hired a thousand people because the work required a thousand people.',
      'They hired because coordination was expensive.',
      'Every layer, every handoff, every status meeting, every document written so somebody else could act.',
      'All of it is the cost of moving a decision from one person to another.',
      'A company exists wherever doing the work inside is cheaper than buying it outside.',
      'The edge of a company is a price. It was never a headcount.',
      'So the number of people was not a measurement of the work.',
      'It was a measurement of the friction around the work.',
      'That is the thing collapsing. Not labor. Coordination.',
      'The work does not disappear. The distance between the pieces of it does.',
      'Which is why the honest number is not twenty percent fewer.',
      'Take a drop shipping company at a thousand people.',
      'Catalog, merchandising, ad operations, tier one support, returns, supplier email, forecasting.',
      'Every one of those is a queue between two people who never meet.',
      'Rebuild it as agents doing the function and a human owning it.',
      'Fourteen because that is roughly how many decisions still need a person on them.',
      'I do not think that is obviously good and I do not think it is fast.',
      'Most companies will do it badly first, and the badly will last years.',
      'But notice where the difficulty actually sits.',
      'The engineering is the easy half and it is close to finished.',
      'The hard half is who decides. Who carries the accountability.',
      'What the remaining people are actually for. What you owe the ones who leave.',
      'It is economics. It is sociology. It is a question about people.',
      'Which is the part almost nobody is working on, and the part that decides how this goes.',
    ],
    closing: 'WE WERE NEVER PAYING FOR THE WORK. WE WERE PAYING FOR THE DISTANCE.',
  },
  {
    slug: 'coding-beats',
    number: 'NOTE 004',
    date: '2026-08-24',
    title: 'Coding Beats',
    summary: 'A public study of rhythm written as code: patterns, motion, and measured sound.',
    source: 'MaloSound',
    body: [
      'I want to study beats that are written as code.',
      'Tools like Strudel make rhythm visible. A beat is not only an audio file. It is tempo, samples, rests, repetition, probability, filters, space, and timing written into a system.',
      'That matters because coded music can be inspected. Change one line and the beat changes. Save the pattern and the idea becomes repeatable. Compare two versions and you can hear what moved.',
      'That is the research question: what happens when a beat is treated like software and sound at the same time?',
      'The study is simple. Build small coded sketches. Document the pattern. Listen to the result. Measure the audio. Map the signal to movement or visuals.',
      'It is also a memory system. I can come back later and see the beat as code: the tempo, the rests, the drum choices, the filter shape, the space, and the pulse.',
      'Someone else can open the same sketch in Strudel, press play, and change it. That is different from posting an audio clip.',
      'The beat is not only something to hear. It is something to inspect.',
      'This is not a claim that AI understands music. It is a public study of how coded rhythm becomes measurable sound and movement.',
      'MaloSound is the public music lane for XIV. This note is the coded rhythm lane.',
      'The first sketch is a slow coded beat in Strudel: readable, playable, and changeable.',
    ],
    closing: 'The beat is not only something to hear. It is something to inspect.',
  },
  {
    slug: 'you-are-not-a-runner',
    number: 'NOTE 003',
    date: '2026-08-16',
    title: 'You Are Not a Runner',
    summary:
      'A note on the sentences that stop us learning something, and why experience outside our heads can change them.',
    source:
      'Jacques Hadamard, An Essay on the Psychology of Invention in the Mathematical Field, 1945.',
    body: [
      'A language model is made of language. That is not an insult. It is the whole description.',
      'It read what we wrote down. It predicts what comes next.',
      'It is very good at that. Most thinking is already written down somewhere.',
      'It has read more than I ever will. It answers in seconds what would take me a week.',
      'I use it every day and I am not being modest about that.',
      'There is nothing under the words. Ask it what it is and you get more words.',
      'For a model the words are not a container. They are the whole thing.',
      'We talk about ourselves the same way.',
      'At the halfway point of the Miami Marathon the course splits.',
      'Left is a finish line and a medal. Right is thirteen more miles.',
      'My legs had stopped working. Another thirteen felt impossible. What have I gotten myself into.',
      'Stop. You cannot do this. You are not a runner.',
      'The first two were about the race.',
      'The third one was about me.',
      'That sentence had been in my head for years. I never once checked it.',
      'You cannot argue with that one. The thing you argue with is the thing that wrote it.',
      'Einstein was asked how he actually thought.',
      'He said words had nothing to do with it. He worked in images. The words had to be found afterwards, laboriously.',
      'Afterwards.',
      'The words came last. They were never the thing.',
      'I went right.',
      'Thirteen more miles with the sentence still going.',
      'It never stopped. It stopped being true.',
      'Nothing in my head did that. Something outside it did.',
      'Months later I sat down to learn this technology from nothing.',
      'Hours at a desk. No crowd, no mile markers, nobody watching if I stopped.',
      'The same sentence showed up. This time I knew what it was.',
      'A model cannot be contradicted from outside its text. You can. You are not only text.',
      'Some days the sentence still wins. But one that has been proven wrong once never sounds the same.',
    ],
    closing: 'WORDS ARE CONTAINERS FOR COMMUNICATION. NOT IDENTITY.',
  },
  {
    slug: 'the-trap-of-time',
    number: 'NOTE 002',
    date: '2026-08-13',
    title: 'The Trap of Time',
    summary:
      'A useful label can become a room you stop trying to leave. A note on time, identity, and using AI to test your limits.',
    source: 'Up, dir. Pete Docter, Pixar, 2009.',
    body: [
      'Time is dangerous when you spend too much of it inside the same story.',
      'At first, a label is useful.',
      'Manager. Analyst. Marketer. Operator. Non-technical. Creative. Business person.',
      'It helps people understand what you do.',
      'But stay inside that label long enough, and it starts to feel like who you are.',
      'That is the trap of time.',
      'You do something for years or decades. You build a life around it. People recognize you for it. You get rewarded for staying consistent. Then one day, the world changes, and the label that once gave you structure starts keeping you in place.',
      'Someone who studied marketing can learn to work with campaign data. Someone from finance can build a small automation. Someone from design can prototype a workflow. The degree remains useful. It becomes context.',
      'That is what I think about with Carl in UP.',
      'He was not just an old man sitting in a house. He was someone frozen in time.',
      'The house was memory. The routine was safety. The dream was still there, but buried under years of grief, repetition, and identity.',
      'Then a push came.',
      'Not a full plan. Not a perfect roadmap. Not permission.',
      'A push.',
      'That is what AI can be for people right now.',
      'A push out of the version of yourself you accepted too early.',
      'Not because AI makes you someone else. Not because it removes the work. But because it lets you question the walls around your current identity.',
      'I am not technical. I am not good with data. I cannot build. That is not my role. It is too late to learn.',
      'How many of those are facts, and how many are just old sentences with time wrapped around them?',
      'The danger is not being bad at something. The danger is letting time convince you that you cannot become anything else.',
      'AI is shrinking the distance between curiosity and execution. You can ask. You can test. You can build. You can learn in private. You can step into rooms that used to feel locked.',
      'But only if you move.',
      'Because the trap is comfortable.',
      'It looks like stability. It sounds like experience. It feels like being realistic.',
      'But sometimes being realistic is just fear with a better outfit.',
      'Do not get caught sleeping inside a label.',
      'The tools are already here.',
      'Sometimes all you need is a push.',
    ],
    closing: 'The only way is UP.',
  },
  {
    slug: 'the-only-thing-paying-attention',
    number: 'NOTE 001',
    date: '2026-08-12',
    title: 'The Only Thing Paying Attention',
    summary:
      'The Axiom passengers were not lazy. They stopped looking up. A note on comfort, agency, and curiosity as an exit.',
    source: 'WALL-E, dir. Andrew Stanton, Pixar, 2008.',
    body: [
      'Everyone posts the Axiom frame to say people got lazy. That is not what the movie is about.',
      'The passengers were fine. Each had a screen a few inches from their face and a pool on board they never knew existed. Nothing was taken from them. They stopped looking up.',
      'Three people I know have three unrelated relationships to the same tool. At work I am more or less required to use it. My sister uses it as a therapist. The woman who rang me up at a sporting goods store last weekend may never have opened it once. Most arguments about whether AI matters are arguments between people whose days look nothing alike.',
      'Which suggests the tool has no fixed depth. It returns something shaped like whatever you walked up to it with - the question you already had, the problem you were already sitting on. The ceiling is set outside the model.',
      "So the failure mode isn't capability. It's comfort.",
      'Nobody takes your agency. You trade it, and the trade is good every single time. The draft comes back fine. The option is already selected. The sentence is already formed. No single exchange is a loss, which is exactly why the total is hard to see. Nothing that felt bad could spread this fast.',
      'WALL-E gave humanity seven hundred years to arrive at that ship.',
      "The captain breaks out of it, and how he does it is the part worth keeping. Nobody warns him. Nobody presents evidence. He gets curious about a plant, and about a word he doesn't know, and the whole system loses him in an afternoon. Curiosity is the only exit the film offers - and it isn't offered as a discipline. It's offered as an accident a person allowed.",
      'SO INSTEAD OF ASKING WHETHER AI IS A BIG DEAL:',
      'If this is a tool - how are we using it?',
      'Are we using it to explore our curiosity, or is it exploring us?',
    ],
    closing: 'Are we using it to explore our curiosity, or is it exploring us?',
  },
];

export function getFieldNote(slug: string) {
  return FIELD_NOTES.find((note) => note.slug === slug);
}
