import type { ExitReason, GateId, Regime } from '@/lib/practice-engine';

export type Locale = 'en' | 'es';

const en = {
  eyebrow: 'XIV / Practice game',
  title: 'Write it down.\nThen see what happens.',
  intro:
    'A practice loop for options decisions. Every price here is fictional, every dollar is simulated, and nothing leaves your browser. Sessions move only when you press advance.',
  boundary:
    'Not advice, not a signal service, not connected to any broker or market feed. Fictional instruments and a simplified pricing model — the point is the discipline, not the numbers.',
  steps: ['Gate', 'Evidence', 'Risk wall', 'Session', 'Receipt'],
  funds: 'Simulated funds',
  peak: 'Peak',
  sessions: 'Sessions',
  seed: 'Seed',
  newSeed: 'New scenario',
  // gate
  gateTitle: 'Green gate',
  gateLead: 'Check the weather before anything else.',
  weather: 'Weather',
  regime: {
    calm: 'Calm',
    normal: 'Normal',
    elevated: 'Elevated',
    extreme: 'Extreme — consider standing down',
  } satisfies Record<Regime, string>,
  quoteAge: 'Quote age',
  spread: 'Spread',
  expiry: 'Practice contract expires in',
  bars: 'bars',
  enterEvidence: 'Go to the evidence trail',
  standDown: 'Stand down',
  standDownHint: 'Standing down is a decision. It gets a receipt too.',
  // evidence
  evidenceTitle: 'Evidence trail',
  evidenceLead: 'Write the assumption before you act on the price.',
  question: 'Grounding question',
  direction: 'Direction',
  longCall: 'Long call',
  longPut: 'Long put',
  reason: 'Why — in one testable sentence',
  reasonPlaceholder: 'e.g. Sixty bars of range, three closes at the top of it, spread is tight.',
  reasonHint: 'At least 20 characters. If you cannot explain it, it is not evidence.',
  invalidation: 'Invalidation — the price where this is wrong',
  scenarioLevel: 'Scenario level — the price the idea is written against',
  holdBars: 'Maximum hold (bars)',
  contracts: 'Contracts',
  atmStrike: 'At-the-money strike',
  premium: 'Premium per contract',
  maxLoss: 'Max loss (premium × 100 × contracts)',
  sealCard: 'Seal the card',
  invalidationSideCall: 'For a long call, invalidation must be below the current price.',
  invalidationSidePut: 'For a long put, invalidation must be above the current price.',
  levelSideCall: 'For a long call, the scenario level must be above the current price.',
  levelSidePut: 'For a long put, the scenario level must be below the current price.',
  // risk
  riskTitle: 'Risk wall',
  riskLead: 'Five gates. Any one fails, the session stops.',
  gate: {
    stale: 'Stale data',
    spread: 'Spread',
    concentration: 'Concentration',
    drawdown: 'Drawdown',
    body: 'Body',
  } satisfies Record<GateId, string>,
  rested: 'I am rested and focused.',
  riskUsd: 'Risk on this card',
  ofFunds: 'of simulated funds',
  allowed: 'All gates pass',
  blocked: 'Blocked — fail closed',
  blockedHint: 'A blocked card can only stand down. That is the rule, not a suggestion.',
  openSession: 'Open the session',
  // live
  liveTitle: 'Session',
  liveLead: 'Time moves when you say so.',
  bar: 'Bar',
  underlying: 'Underlying',
  mark: 'Contract mark',
  unrealized: 'Unrealized',
  barsLeft: 'Bars to expiry',
  advance: 'Advance one bar',
  close: 'Close the position',
  invalidationHitBanner: 'Invalidation hit. Your own card says the thesis is wrong.',
  ignoredBanner: 'You advanced past your invalidation. The receipt will record it.',
  levelHitBanner: 'Scenario level reached.',
  expiredBanner: 'The contract expired. The position closed at intrinsic value.',
  // after
  afterTitle: 'Receipt',
  afterLead: 'Before and after, sealed side by side.',
  before: 'BEFORE',
  after: 'AFTER',
  exit: 'Exit',
  exitReason: {
    target: 'scenario level',
    invalidation: 'invalidation respected',
    expiry: 'expiry',
    manual: 'closed by hand',
    stand_down: 'stood down',
  } satisfies Record<ExitReason, string>,
  result: 'Result',
  ruleFollowed: 'Rule followed',
  ruleBroken: 'Rule broken',
  lesson: 'What did this session teach?',
  lessonPlaceholder:
    'One sentence. Not what happened — what you would do differently, or keep doing.',
  sealReceipt: 'Seal the receipt',
  hash: 'hash',
  // archive
  archiveTitle: 'Archive',
  archiveLead: 'Patterns live here. Not P&L — patterns.',
  empty: 'No receipts yet. The first one is the hardest to write.',
  winRate: 'Win rate',
  expectancy: 'Expectancy',
  ruleRate: 'Rule-follow rate',
  standDowns: 'Stand-downs',
  worstDd: 'Worst run',
  net: 'Net (simulated)',
  perTrade: 'R per trade',
  copyJson: 'Copy journal as JSON',
  copied: 'Copied',
  reset: 'Reset everything',
  resetConfirm: 'Reset? This deletes every receipt in this browser.',
  yes: 'Yes, reset',
  no: 'Keep it',
  yesRule: 'yes',
  noRule: 'no',
  home: 'Back to XIV',
};

const es: typeof en = {
  eyebrow: 'XIV / Juego de práctica',
  title: 'Escríbelo.\nDespués mira qué pasa.',
  intro:
    'Un ciclo de práctica para decisiones con opciones. Cada precio es ficticio, cada dólar es simulado y nada sale de tu navegador. Las sesiones avanzan solo cuando pulsas avanzar.',
  boundary:
    'No es asesoría, no es un servicio de señales y no está conectado a ningún bróker ni fuente de mercado. Instrumentos ficticios y un modelo de precios simplificado: lo que importa es la disciplina, no los números.',
  steps: ['Puerta', 'Evidencia', 'Muro de riesgo', 'Sesión', 'Recibo'],
  funds: 'Fondos simulados',
  peak: 'Máximo',
  sessions: 'Sesiones',
  seed: 'Semilla',
  newSeed: 'Nuevo escenario',
  gateTitle: 'Puerta verde',
  gateLead: 'Mira el clima antes que nada.',
  weather: 'Clima',
  regime: {
    calm: 'Tranquilo',
    normal: 'Normal',
    elevated: 'Elevado',
    extreme: 'Extremo — considera no operar',
  },
  quoteAge: 'Edad de la cotización',
  spread: 'Spread',
  expiry: 'El contrato de práctica vence en',
  bars: 'barras',
  enterEvidence: 'Ir al sendero de evidencia',
  standDown: 'No operar',
  standDownHint: 'No operar es una decisión. También recibe un recibo.',
  evidenceTitle: 'Sendero de evidencia',
  evidenceLead: 'Escribe la suposición antes de actuar sobre el precio.',
  question: 'Pregunta de anclaje',
  direction: 'Dirección',
  longCall: 'Call comprado',
  longPut: 'Put comprado',
  reason: 'Por qué — en una frase comprobable',
  reasonPlaceholder:
    'p. ej. Sesenta barras en rango, tres cierres en la parte alta, el spread está ajustado.',
  reasonHint: 'Mínimo 20 caracteres. Si no puedes explicarlo, no es evidencia.',
  invalidation: 'Invalidación — el precio donde esto está mal',
  scenarioLevel: 'Nivel de escenario — el precio contra el que se escribe la idea',
  holdBars: 'Tenencia máxima (barras)',
  contracts: 'Contratos',
  atmStrike: 'Strike en el dinero',
  premium: 'Prima por contrato',
  maxLoss: 'Pérdida máxima (prima × 100 × contratos)',
  sealCard: 'Sellar la tarjeta',
  invalidationSideCall:
    'Para un call comprado, la invalidación debe estar por debajo del precio actual.',
  invalidationSidePut:
    'Para un put comprado, la invalidación debe estar por encima del precio actual.',
  levelSideCall:
    'Para un call comprado, el nivel de escenario debe estar por encima del precio actual.',
  levelSidePut:
    'Para un put comprado, el nivel de escenario debe estar por debajo del precio actual.',
  riskTitle: 'Muro de riesgo',
  riskLead: 'Cinco puertas. Si una falla, la sesión se detiene.',
  gate: {
    stale: 'Datos viejos',
    spread: 'Spread',
    concentration: 'Concentración',
    drawdown: 'Drawdown',
    body: 'Cuerpo',
  },
  rested: 'Estoy descansado y enfocado.',
  riskUsd: 'Riesgo en esta tarjeta',
  ofFunds: 'de los fondos simulados',
  allowed: 'Todas las puertas pasan',
  blocked: 'Bloqueado — cierra por defecto',
  blockedHint: 'Una tarjeta bloqueada solo puede no operar. Es la regla, no una sugerencia.',
  openSession: 'Abrir la sesión',
  liveTitle: 'Sesión',
  liveLead: 'El tiempo avanza cuando tú lo dices.',
  bar: 'Barra',
  underlying: 'Subyacente',
  mark: 'Precio del contrato',
  unrealized: 'No realizado',
  barsLeft: 'Barras hasta el vencimiento',
  advance: 'Avanzar una barra',
  close: 'Cerrar la posición',
  invalidationHitBanner: 'Invalidación tocada. Tu propia tarjeta dice que la tesis está mal.',
  ignoredBanner: 'Avanzaste más allá de tu invalidación. El recibo lo registrará.',
  levelHitBanner: 'Nivel de escenario alcanzado.',
  expiredBanner: 'El contrato venció. La posición cerró a valor intrínseco.',
  afterTitle: 'Recibo',
  afterLead: 'Antes y después, sellados lado a lado.',
  before: 'ANTES',
  after: 'DESPUÉS',
  exit: 'Salida',
  exitReason: {
    target: 'nivel de escenario',
    invalidation: 'invalidación respetada',
    expiry: 'vencimiento',
    manual: 'cerrado a mano',
    stand_down: 'no operó',
  },
  result: 'Resultado',
  ruleFollowed: 'Regla cumplida',
  ruleBroken: 'Regla rota',
  lesson: '¿Qué enseñó esta sesión?',
  lessonPlaceholder: 'Una frase. No lo que pasó: lo que harías distinto, o lo que mantendrías.',
  sealReceipt: 'Sellar el recibo',
  hash: 'hash',
  archiveTitle: 'Archivo',
  archiveLead: 'Aquí viven los patrones. No el P&L: los patrones.',
  empty: 'Todavía no hay recibos. El primero es el más difícil de escribir.',
  winRate: 'Tasa de acierto',
  expectancy: 'Expectativa',
  ruleRate: 'Cumplimiento de reglas',
  standDowns: 'Sin operar',
  worstDd: 'Peor racha',
  net: 'Neto (simulado)',
  perTrade: 'R por operación',
  copyJson: 'Copiar diario como JSON',
  copied: 'Copiado',
  reset: 'Borrar todo',
  resetConfirm: '¿Borrar? Esto elimina todos los recibos de este navegador.',
  yes: 'Sí, borrar',
  no: 'Conservar',
  yesRule: 'sí',
  noRule: 'no',
  home: 'Volver a XIV',
};

export const PLAY_COPY: Record<Locale, typeof en> = { en, es };
